CREATE TABLE IF NOT EXISTS info_hash (
  id      BIGINT AUTO_INCREMENT COMMENT 'id',
  content VARCHAR(256) DEFAULT '' COMMENT '内容',
  PRIMARY KEY (id)
)AUTO_INCREMENT = 1000,COMMENT = 'info_hash';

CREATE TABLE IF NOT EXISTS  node (
  id      BIGINT AUTO_INCREMENT COMMENT 'id',
  node_id VARCHAR(20) DEFAULT '' COMMENT 'node_id',
  ip VARCHAR(32) DEFAULT '' COMMENT 'ip',
  port INT DEFAULT 0 COMMENT 'port',
  PRIMARY KEY (id)
)AUTO_INCREMENT = 1000,COMMENT = 'node';



